### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by GoNotCougsWA** [InventivetalentDev/NickNamer#27] opened 2016-07-20 04:50 UTC
## What steps will reproduce the problem?  
When I use /nick <Nick> and Run
## What were you expecting to happen? What happened instead?  
Not to not that. There is a Chunk error were I Run 
## What version of the plugin are you using? *Type /version Plugin Name 
3.12.2
## What Spigot version are you using? *Type /version*  
1.8.8-R0.1-SNAPSHOT
## What plugins are you using? *Type /plugins*  
WorldEdit, WorldGuard, Multiverse-Core, Vault, and more
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Nope no Error Log
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Nope
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Nope I am not using buneecord

**Comment by InventivetalentDev** [comment] 2016-07-20 11:03
Duplicate of the last issue you created and #21 

This is an issue with the minecraft client and currently has no reliable solution.
Press `F3-A` to reload the world or disable _selfUpdate_ in the config.

**Closed by InventivetalentDev** 2016-07-20 11:03 UTC
Labels: duplicate, invalid
