### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by Jakaboii** [InventivetalentDev/NickNamer#114] opened 2020-04-13 16:43 UTC
## What steps will reproduce the problem?  
1. Enable "sql" on the storage.type option in config.yml
2. Join the server
3. wait

## What version of the plugin are you using?
3.18.1-SNAPSHOT

## What Spigot version are you using?
Paper 1.8.8 (latest release)

## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/50416254/79139113-9f152a00-7dad-11ea-9581-a07cef55a14d.png)

## Do you have an error log?
https://hatebin.com/pdpeqmstan

## Did your client crash?
No

## Additional information?
I'm using [Flamecord ](https://www.mc-market.org/resources/13492) & I don't think this happened on previous versions, I can't remember though
The error didn't happen when I changed storage.type to "local"
This still may not be caused by NickNamer, as I actually don't exactly know how to reproduce this, I just said was I'm pretty sure happened

**Comment by InventivetalentDev** [comment] 2020-04-14 09:40
I'm guessing this might be caused by the database closing the connection and the plugin not trying to reconnect again.  
Since you said you have to "wait" for this to happen, I guess this just happens randomly over time without any interaction?

**Comment by Jakaboii** [comment] 2020-04-14 11:56
Yea, it just happens randomly over time

**Comment by Jadiction** [comment] 2020-05-16 10:44
I get this as well - https://pastebin.com/raw/UDv5nyb1

Although, I'm testing for plugin conflicts that may be causing this.

**Comment by Jadiction** [comment] 2020-05-16 17:48
Nevermind, there doesn't appear to be any plugin conflicts. I can reproduce this with only: LuckPerms, NickNamer, PacketListenerAPI, and PlaceholderAPI.

**Comment by Jadiction** [comment] 2020-07-16 03:01
This is still an issue that prevents me from using the plugin. I'll test it on 1.16.2 when it comes out.

**Closed** 2020-09-26 03:40 UTC
Labels: wontfix
