### ISSUE TITLE
Using NickNamer with EssentialsXChat

### ISSUE THREAD

**Issue by wgetgoose** [InventivetalentDev/NickNamer#121] opened 2020-05-08 19:17 UTC
## What steps will reproduce the problem?  
1. Install NickNamer, EssentailsX, and EssentialsXChat
2. Disable EssentialsX nickname feature and rebind using aliases.
3. /nickname binds to NickNamer, but /nick can't seem to work
## What were you expecting to happen? What happened instead?  
Expecting /nick to use NickNamer's /nick, instead just shows "disabled"
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Nicknamer: 3.18.2 Snapshot, EssentialsX: 2.17.2.77, EssentialsXChat: 2.17.2.77
## What Spigot version are you using? *Type /version*  
git-Paper-261
## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/64772046/81441162-209a7680-9126-11ea-9e20-cb27aad20c35.png)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Tried solution [here](https://github.com/InventivetalentDev/NickNamer/issues/113), no success. Commands.yml seen below
```
command-block-overrides: []
aliases:
    nickname:
    - "nicknamer:nick $1-"
    nick:
    - nickname $1-
    away:
  - essentials:afk 
```
and Config.yml in a pastebin [here](https://pastebin.com/N1H2aH9f)

Notes: I'm worried NickNamer won't work with EssentialsXChat, in the sense that displaynames will not output to the chat because EssentialsXChat is trying to read displaynames from Essentials. I am unsure of how to change where EssentialsXChat reads names from. I also can't quite figure out the aliases. Thanks!

**Comment by GooseBinary** [comment] 2020-05-08 20:34
Kind of fixed. Forgot to get Player API / PAPI ([here](https://www.spigotmc.org/resources/placeholderapi.6245/). I want to bind /nick to nicknamer's /nick. But, if I enable /nick in the Essentials config, it uses the Essentials nickname system. But if I disable /nick in the config, the alias doesn't work and nick is just "disabled." Any help would be super appreciated.

**Comment by Th3Shadowbroker** [comment] 2020-05-08 21:27
Hey @GooseBinary,
I were unable to replicated your problem with the `/nick` command. I set everything up as I explained in #113 and everything worked as expected. The message I get when I'm using the nick command looks as follows:

*Essentials (No aliases setup, no command disabled)*:
![image](https://user-images.githubusercontent.com/8280615/81449148-e78ef000-917f-11ea-8275-0ecb086c60ca.png)

*NickNamer (Aliases setup, nickname command disabled)*:
![image](https://user-images.githubusercontent.com/8280615/81449173-f70e3900-917f-11ea-90dc-7b222ec66428.png)

Regarding the chat thingy:
During my tests NickNamer worked fine with EssentialsXChat, after enabling the option to replace names in all outgoing messages. (`replace > chat > out`)

**Comment by GooseBinary** [comment] 2020-05-08 21:32
Can you show me your aliases exactly? Also, can I see your #disabled-commands in essentials? That would help a ton. Thanks!

**Comment by GooseBinary** [comment] 2020-05-08 21:41
Here are both of mine now for reference:
     Commands.yml
```
command-block-overrides: []
aliases:
    nickname:
    - "nicknamer:nickname $1-"
    nick:
  - nickname $1-
    away:
  - essentials:afk`
```
    config.yml disabled section
```
disabled-commands:
- nickname
```

**Comment by Th3Shadowbroker** [comment] 2020-05-09 06:56
*commands.yml*
```yaml
command-block-overrides: []
aliases:
  icanhasbukkit:
  - version $1-
  nick:
  - nickname $1-
ignore-vanilla-permissions: false
```
`/nick` as well as `/nickname` work perfectly fine with this setup. **Without** this part:
```yaml
  nickname:
  - "nicknamer:nickname $1-"
```

*EssentialsX config.yml*
```yaml
...
disabled-commands:
   - nickname
...
```

**Comment by GooseBinary** [comment] 2020-05-09 07:10
Literally copied and pasted both your commands.yml setup and your essentialsx config.yml and /nick still uses essentials nickname system.

**Comment by GooseBinary** [comment] 2020-05-09 07:15
Here's my NickNamer config.yml 
`replace:
  chat:
    # Replace names in messages sent by players
    player: true

    # Replaces names in ALL outgoing messages
    out: true
    in:
      # Replace real names in incoming commands with the player's nickname
      command: false
      # Replace incoming command nicknames with the player's real name
      # (If multiple players use the same nickname, it will default to the first available player's real name)
      commandReverse: false

      # Replace real names in general (non-command) incoming messages with the player's nickname
      general: false
      # Replace incoming nicknames with the player's real name
      # (If multiple players use the same nickname, it will default to the first available player's real name)
      generalReverse: false
  scoreboard: false
  scoreboardScore: false
  scoreboardTeam: false
  tabComplete:
    chat: false

updateSelf: true

# Whether to allow offline players as command targets when changing nicks/skins
allowOfflineTargets: false

random:
  join:
    nick: false
    skin: false
  nick:
  - "inventivetalent"
  - "md_5"
  - mojang: # Name category
    - "jeb_"
    - "Notch"
    - "Dinnerbone"
  skin:
  - "md_5"
  - "inventivetalent"

names:
  # Format for names, for example '&9%s' would color all names blue. Note: names can't be longer than 16 charcters and will be shortened.
  format: "%s"

  # Format for names in chat messages
  chatFormat: "%s&r"

  # Allow names with spaces. This replaces underscores ("_") in names with a space - Double underscores ("__") are displayed as single underscores.
  spaces: true

#Enable this if this server is behind a BungeeCord server
bungeecord: false

storage:
  # Storage type
  # - temporary
  #     saves all data in memory until the server is stopped
  # - local (recommended)
  #     creates a local database
  # - sql
  #     uses an SQL server
  # - redis
  #     uses a Redis server
  type: "local"
  sql:
    address: "jdbc:mysql://localhost:3306/minecraft"
    user: ""
    pass: ""
  redis:
    host: "localhost"
    port: 6379
    pass: ""
    max-connections: 4

execution:

  on-nick:
    # Commands that should be executed by the console when players nick themselves.
    console:
      #- aCommand

    # Commands that should be executed by players when they nick themselves.
    player:
      #- ping

  on-unnick:
    # Commands that should be executed by the console when players unnick themselves.
    console:
      #- aCommand

    # Commands that should be executed by players when they unnick themselves.
    player:
      #- ping

messages:
  command:
    name:
      changed: "&aChanged &b%player%'s &aname to &b%name%&a."
      cleared: "&aCleared &b%player%'s &aname"
      list:
        used: "&eUsed names:"
        format: "&r%s &eis used by&r %s"
      error:
        length: "&cThe specified name is too long"
        category:
          unknown: "&cUnknown category: %s"
        list:
          empty: "&cThere are no used names"
    skin:
      changing: "&7Changing &b%player%'s &7skin to &b%skin%'s&7 skin..."
      changed: "&aChanged &b%player%'s &askin to &b%skin%'s&a skin."
      cleared: "&aCleared &b%player%'s &askin"
      list:
        used: "&eUsed skins:"
        format: "&r%s &eis used by&r %s"
      error:
        length: "&cThe specified skin is too long"
        category:
          unknown: "&cUnknown category: %s"
        list:
          empty: "&cThere are no used skins"
    offlineInfo: "&eThe requested player is currently offline. Changes will be applied when they come online."
    error:
      unknown: "&cUnknown error while executing command. See console for details."
      permission: "&cYou are missing the following permission: %s"
      illegalSender: "&cThis command is only available to players"
      unhandled: "&cInternal exception. See console for details."
      length:
       short: "&cMissing arguments. Usage: %s"
       long: "&cToo many arguments. Usage: %s"
      parse: "&cFailed to parse argument '%s' to %s"
      target:
        notFound: "&cPlayer could not be found"

# Disable the features below, if you're only interested in utilizing the API.
pluginFeatures:
  commands:
    general: true
    nick: true
    skin: true
`

**Comment by Th3Shadowbroker** [comment] 2020-05-09 07:20
Please define `uses essentials nickname system`. If you still see a nickname you set using Essentials then you have to remove it from your Essentials profile (It's saved under `plugins/Essentials/userdata/<your uuid>.yml`) and simply remove the `nickname` from there.

**Comment by GooseBinary** [comment] 2020-05-09 07:25
using `/nick`
![image](https://user-images.githubusercontent.com/64772046/81467149-8bca6400-918b-11ea-84dc-aedcfefa33e0.png)
![image](https://user-images.githubusercontent.com/64772046/81467152-91c04500-918b-11ea-8166-839bd464dd65.png)
using `/nickname`
![image](https://user-images.githubusercontent.com/64772046/81467157-a0a6f780-918b-11ea-8576-c9a3bb087086.png)
![image](https://user-images.githubusercontent.com/64772046/81467160-a3a1e800-918b-11ea-9809-c802c24827d8.png)

**Comment by GooseBinary** [comment] 2020-05-09 07:35
Using /nick also breaks chat nicknames.

**Comment by Th3Shadowbroker** [comment] 2020-05-09 07:37
Mhhh... 🤔 
I see. There isn't much left that could be the cause of this problem.
Have you always used the `/reload` command after making changes to the config-files?
If that's the case then we got our problem, as commands require a complete restart.
Reloading is a cardinal sin and chances are pretty high that it breaks something.

**Comment by Th3Shadowbroker** [comment] 2020-05-10 07:00
Does the problem still exist?

**Comment by GooseBinary** [comment] 2020-05-10 08:15
I've tried reloading and restarting. /nick is still broken. It isn't really a big deal as /nickname still works completely fine.

**Comment by GooseBinary** [comment] 2020-05-16 22:07
Reinstalled server and everything works fine. Never reload essentials guys, breaks it for sure!

**Comment by Th3Shadowbroker** [comment] 2020-05-17 04:11
Great to hear that! 
As I said. Reloading is never a good idea. I know it's tempting, but the majority of plugins isn't able to handle reloads. If there are no further problems you can close this issue.

**Closed** 2020-07-25 06:14 UTC
Labels: wontfix
