### ISSUE TITLE
Random nick and random skin bug

### ISSUE THREAD

**Issue by PhilTheRanter** [InventivetalentDev/NickNamer#14] opened 2016-07-05 14:14 UTC
**## What steps will reproduce the problem?**  
1. When I am /op I **do** have the permission to random nick and random skin.
2. When my players who have the permission 'nick.command.name.random' and the 'nick.command.skin.random' try to use the command, it says that they are missing those permissions.

**## What were you expecting to happen? What happened instead?** 
It is supposed to work and my players should be able to use random nick and random skin and it always says 'Missing the permissions'

**## What version of the plugin are you using?**
NickNamer version: 3.11.7

**## What Spigot version are you using?**
Spigot version: git-Spigot-fdc1440-53fac9f MC: 1.8.8

**## What plugins are you using?**
My plugin list is private but I have tried to use the nicknamer without any plugins only with a permission plugun called 'LordPermissions' and it did not work.

**## Do you have an error log?**
No, I do not have any error log.

**## Did your client crash?**
No, it did not.

**## Additional information?  (Are you using Bungeecord? Did it work in previous versions? etc.)**
I am using bungeecord and I have not tried to use it on previous versions.

**Comment by InventivetalentDev** [comment] 2016-07-05 17:18
Your players also need the general name/skin permissions, including the permissions for specific names:  
![](https://i.inventivetalent.org/2016/07/477b89c27b_chrome_2016-07-05_19-18-06.png)

**Comment by PhilTheRanter** [comment] 2016-07-05 18:11
Still not working.

**Comment by PhilTheRanter** [comment] 2016-07-05 19:14
Something like " missing the permission 'nick.command.name.random' " and " 'nick.command.skin.random' "

**Comment by InventivetalentDev** [comment] 2016-07-05 19:54
Please post a screenshot of the message. Have you tried any other permission plugins (e.g. PermissionsEx)? Might be because of your current permission plugin.

**Comment by PhilTheRanter** [comment] 2016-07-05 20:11
Well now it says that I'm missing the following permission: 'nick.other'.

**Comment by InventivetalentDev** [comment] 2016-07-05 20:16
There might be an issue with the command in that case.

**Comment by PhilTheRanter** [comment] 2016-07-05 20:17
Ok, is that an issue of the plugin or of my config etc.?

**Comment by InventivetalentDev** [comment] 2016-07-05 20:18
Issue with the plugin. Unrelated to the one you reported, but it's not intended to require every player to have the 'nick.other' permission.

**Comment by PhilTheRanter** [comment] 2016-07-05 20:20
Alright, may you fix it if possible?

**Comment by InventivetalentDev** [comment] 2016-07-05 20:23
I'm already working on it, please be patient.

**Comment by PhilTheRanter** [comment] 2016-07-05 20:25
Already, I was just asking. Sorry about that and thank you.

**Comment by InventivetalentDev** [comment] 2016-07-05 20:31
The nick.other permission issues is fixed in v3.11.8. The issues you had were caused by missing permissions, so that should work fine now.

**Comment by PhilTheRanter** [comment] 2016-07-05 20:47
Yes it works now, but now it says that I am missing the permission to 'nick.skin' though I have this permission set to the groups.

**Comment by InventivetalentDev** [comment] 2016-07-05 21:13
Do you have 'nick.skin.<skin name>'?

**Comment by PhilTheRanter** [comment] 2016-07-05 21:18
I have 'nick.skin.*' set as a permission.

**Comment by InventivetalentDev** [comment] 2016-07-05 21:22
Well, it works absolutely fine for me (With permissions 'nick.command.skin' & 'nick.skin.*', so there's probably a problem with your permissions.

**Comment by PhilTheRanter** [comment] 2016-07-05 22:01
Oh sorry, I wrote nick.skin* and forgot the dot before the star. Thank you very much for fixing it, everything seems to be working fine now.

**Comment by InventivetalentDev** [comment] 2016-07-05 22:01
Nice :)

**Closed by InventivetalentDev** 2016-07-05 22:01 UTC
