### ISSUE TITLE
Disable changing nametag (above player head)

### ISSUE THREAD

**Issue by ZachTheDev** [InventivetalentDev/NickNamer#151] opened 2021-03-20 05:12 UTC
**Is your feature request related to a problem? Please describe.**

I am using your plugin in conjunction with [TAB](https://www.spigotmc.org/resources/tab-1-7-x-1-16-5-free-version.57806/). TAB has a system that creates custom nametags, but when I nick a player, the nametag is still there. So there is a duplicate nametag since TAB creates one.

**Describe the solution you'd like**

I'd like the ability to have it so that NickNamer won't touch the tag so that TAB can do its thing.

**Describe alternatives you've considered**

Switching to another nick plugin, but its bloated and has features I don't want. Yours is clean and easy to use.

**Additional context**

**Comment by ItzRonaldMLG** [comment] 2021-03-26 16:39
If you want the nametag to be changed, just use PlaceholderAPI and do this like i do in the TAB plugin :)
This is how i integrated it. Only issue with TAB is and i just contacted him is the tag and health dont update, this might be fixed in a few days.
Do change: https://prnt.sc/10wb45j
Don't change: https://prnt.sc/10wb51w

**Comment by ZachTheDev** [comment] 2021-03-26 16:46
> If you want the nametag to be changed, just use PlaceholderAPI and do this like i do in the TAB plugin :)
> This is how i integrated it. Only issue with TAB is and i just contacted him is the tag and health dont update, this might be fixed in a few days.
> Do change: https://prnt.sc/10wb45j
> Don't change: https://prnt.sc/10wb51w

I have the same settings as you. My customtabname and customtagname are set to the placeholderapi for nickname, that's why I went with this one. The issue is that there are overlapping name tags. TAB creates its own using armor stands, but the vanilla one is changed and set by what I think is nicknamer. The thing is, it only happens when after a reboot and the player logs in for the first time since that boot. After a relog, it fixes. The same thing happens with the custom join message I have using ChatEx (again using placeholderapi for the nickname), it shows the regular player name first, then after a relog it works as intended.

**Comment by ItzRonaldMLG** [comment] 2021-03-26 18:23
I think i have something similar: https://prnt.sc/10wdc3y
But after a relog its fixed, i asked the TAB dev though. We will see shat he can do. I think it might be the plugin TAB thats the problem with this.

**Comment by ItzRonaldMLG** [comment] 2021-03-26 20:27
I see what you ment, TAB uses armor stands for the names above the player.
Nicknamer or the API is conflicting with the methode used by TAB or vice versa, removing name display option for nicknamer and using the placeholders on TAB would fix it.

**Comment by ZachTheDev** [comment] 2021-03-26 20:49
> I see what you ment, TAB uses armor stands for the names above the player.
> Nicknamer or the API is conflicting with the methode used by TAB or vice versa, removing name display option for nicknamer and using the placeholders on TAB would fix it.
> But after a rejoin it is fixed and doesnt overlap

Exactly, and I was assuming that method is something in Nicknamer since TAB, in the documentation, says it tries to override other plugins from doing stuff like that.

**Comment by ItzRonaldMLG** [comment] 2021-03-26 21:00
I understand, i dont know were the issue is because it does work if you rejoin, Then it will use TAB plugin's methode and the Floating double name is gone.

**Comment by ItzRonaldMLG** [comment] 2021-03-27 14:29
I had contact with TAB plugin dev, it looks like this code: https://github.com/InventivetalentDev/NickNamer/blob/master/API/src/main/java/org/inventivetalent/nicknamer/api/PacketListener.java#L106-L109
Does prevent displaying the name tag properly.
Is there a change there could be an option to disable it and the plugin nicknamer still works with placeholders and all other features?

**Comment by InventivetalentDev** [comment] 2021-03-27 16:25
I can add an option to disable the part modifying those packets, but that will also disable skin changes.

**Comment by ZachTheDev** [comment] 2021-03-27 16:26
> I can add an option to disable the part modifying those packets, but that will also disable skin changes.

Thanks for the reply! That works for my use case, so that would be awesome.

**Comment by ItzRonaldMLG** [comment] 2021-03-27 16:34
Does it also disable skins if you use skinrestorer? ;(

**Comment by InventivetalentDev** [comment] 2021-03-27 16:36
> Does it also disable skins if you use skinrestorer? ;(

Pretty sure they use their own packet stuff, so shouldn't affect that

**Comment by ItzRonaldMLG** [comment] 2021-03-27 16:42
That would be very very apricated :D

**Comment by ItzRonaldMLG** [comment] 2021-03-27 19:05
Well i did this: https://prnt.sc/10xb2wp
Result same (white name is from Nicknamer): https://prnt.sc/10xb5jl
Or did i do something wrong?

**Comment by InventivetalentDev** [comment] 2021-03-27 19:14
it shouldn't modify those packets anymore now, not sure why it's still not working

**Comment by ItzRonaldMLG** [comment] 2021-03-27 19:21
Another thing, after a restart of the server you dont have a nickname anymore..

**Comment by ItzRonaldMLG** [comment] 2021-06-02 18:19
Yes, but apparently wont be fixed.

**Comment by Tactryl3** [comment] 2021-09-23 01:46
> Well i did this: https://prnt.sc/10xb2wp
> Result same after relog (white name is from Nicknamer): https://prnt.sc/10xb5jl
> Or did i do something wrong?

I am having this issue as well. Is there a way to disable the nametag that Nicknamer injects?

**Comment by Tactryl3** [comment] 2021-09-23 02:08
![image](https://user-images.githubusercontent.com/71281742/134444927-c27e20b2-0690-4923-b924-cd3cb20c10d8.png)
This is an image of my issue. The one with [Admin] in front of it is managed by TAB. The other one is managed by Nicknamer. Can there be a way to disable this?

**Closed** 2022-03-03 00:33 UTC
Labels: wontfix
